/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-06-03 04:02:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.eazydeals.entities.Message;
import com.eazydeals.dao.ProductDao;
import com.eazydeals.dao.CartDao;
import com.eazydeals.entities.Admin;
import com.eazydeals.entities.Cart;
import com.eazydeals.dao.CartDao;
import com.eazydeals.entities.User;
import java.util.List;
import com.eazydeals.entities.Category;
import com.eazydeals.helper.ConnectionProvider;
import com.eazydeals.dao.CategoryDao;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Components/navbar.jsp", Long.valueOf(1717386839216L));
    _jspx_dependants.put("/Components/common_css_js.jsp", Long.valueOf(1717386839215L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(10);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.eazydeals.entities.Category");
    _jspx_imports_classes.add("com.eazydeals.dao.CategoryDao");
    _jspx_imports_classes.add("com.eazydeals.dao.CartDao");
    _jspx_imports_classes.add("com.eazydeals.entities.Message");
    _jspx_imports_classes.add("com.eazydeals.dao.ProductDao");
    _jspx_imports_classes.add("com.eazydeals.entities.Cart");
    _jspx_imports_classes.add("com.eazydeals.entities.User");
    _jspx_imports_classes.add("com.eazydeals.helper.ConnectionProvider");
    _jspx_imports_classes.add("com.eazydeals.entities.Admin");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error_exception.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

User activeUser = (User) session.getAttribute("activeUser");
if (activeUser == null) {
	Message message = new Message("You are not logged in! Login first!!", "error", "alert-danger");
	session.setAttribute("message", message);
	response.sendRedirect("login.jsp");
	return;  
}
String from = (String)session.getAttribute("from");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Checkout</title>\n");
      out.write("<!--CSS-->\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM\" crossorigin=\"anonymous\">\n");
      out.write("<!--font awesome-->\n");
      out.write("<!--<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("-->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/style.css\"/>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--JavaScript-->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"JS/script.js\"></script>\n");
      out.write("\n");
      out.write("<!--jQuery-->\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\n");
      out.write("<!--sweet alert-->\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!--navbar -->\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

User user = (User) session.getAttribute("activeUser");
Admin admin = (Admin) session.getAttribute("activeAdmin");

CategoryDao catDao = new CategoryDao(ConnectionProvider.getConnection());
List<Category> categoryList = catDao.getAllCategories();

      out.write("\n");
      out.write("<style>\n");
      out.write(".navbar {\n");
      out.write("	font-weight: 500;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link {\n");
      out.write("	color: rgb(255 255 255/ 100%) !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-menu {\n");
      out.write("	background-color: #ffffff !important;\n");
      out.write("	border-color: #949494;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-menu li a:hover {\n");
      out.write("	background-color: #808080 !important;\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<nav class=\"navbar navbar-expand-lg custom-color\" data-bs-theme=\"dark\">\n");
      out.write("\n");
      out.write("	<!-- admin nav bar -->\n");
      out.write("	");

	if (admin != null) {
	
      out.write("\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<a class=\"navbar-brand\" href=\"admin.jsp\"><i\n");
      out.write("			class=\"fa-sharp fa-solid fa-house\" style=\"color: #ffffff;\"></i>&ensp;EazyDeals</a>\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("			data-bs-target=\"#navbarSupportedContent\"\n");
      out.write("			aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("			aria-label=\"Toggle navigation\">\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("		</button>\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("\n");
      out.write("			<div class=\"container text-end\">\n");
      out.write("				<ul class=\"navbar-nav justify-content-end\">\n");
      out.write("					<li class=\"nav-item\"><button type=\"button\"\n");
      out.write("							class=\"btn nav-link\" data-bs-toggle=\"modal\"\n");
      out.write("							data-bs-target=\"#add-category\"><i class=\"fa-solid fa-plus fa-xs\"></i>Add Category</button></li>\n");
      out.write("					<li class=\"nav-item\"><button type=\"button\"\n");
      out.write("							class=\"btn nav-link\" data-bs-toggle=\"modal\"\n");
      out.write("							data-bs-target=\"#add-product\"><i class=\"fa-solid fa-plus fa-xs\"></i>Add Product</button></li>\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" aria-current=\"page\"\n");
      out.write("						href=\"admin.jsp\">");
      out.print(admin.getName());
      out.write("</a></li>\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" aria-current=\"page\"\n");
      out.write("						href=\"LogoutServlet?user=admin\"><i\n");
      out.write("							class=\"fa-solid fa-user-slash fa-sm\" style=\"color: #fafafa;\"></i>&nbsp;Logout</a></li>\n");
      out.write("				</ul>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	");

	} else {
	
      out.write("\n");
      out.write("\n");
      out.write("	<!-- end -->\n");
      out.write("\n");
      out.write("	<!-- for all -->\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<a class=\"navbar-brand\" href=\"index.jsp\"><i\n");
      out.write("			class=\"fa-sharp fa-solid fa-house\" style=\"color: #ffffff;\"></i>&ensp;EazyDeals</a>\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("			data-bs-target=\"#navbarSupportedContent\"\n");
      out.write("			aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("			aria-label=\"Toggle navigation\">\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("		</button>\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("			<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"products.jsp\"\n");
      out.write("					role=\"button\" aria-expanded=\"false\"> Products </a>\n");
      out.write("				<li class=\"nav-item dropdown\"><a\n");
      out.write("					class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\"\n");
      out.write("					data-bs-toggle=\"dropdown\" aria-expanded=\"false\"> Category </a>\n");
      out.write("					<ul class=\"dropdown-menu\">\n");
      out.write("						<li><a class=\"dropdown-item\" href=\"products.jsp?category=0\">All\n");
      out.write("								Products</a></li>\n");
      out.write("						");

						for (Category c : categoryList) {
						
      out.write("\n");
      out.write("						<li><a class=\"dropdown-item\"\n");
      out.write("							href=\"products.jsp?category=");
      out.print(c.getCategoryId());
      out.write('"');
      out.write('>');
      out.print(c.getCategoryName());
      out.write("</a></li>\n");
      out.write("						");

						}
						
      out.write("\n");
      out.write("					</ul></li>\n");
      out.write("			</ul>\n");
      out.write("			<form class=\"d-flex pe-5\" role=\"search\" action=\"products.jsp\"\n");
      out.write("				method=\"get\">\n");
      out.write("				<input name=\"search\" class=\"form-control me-2\" size=\"50\"\n");
      out.write("					type=\"search\" placeholder=\"Search for products\" aria-label=\"Search\"\n");
      out.write("					style=\"background-color: white !important;\">\n");
      out.write("				<button class=\"btn btn-outline-light\" type=\"submit\">Search</button>\n");
      out.write("			</form>\n");
      out.write("\n");
      out.write("			<!-- when user is logged in -->\n");
      out.write("			");

			if (user != null) {
				CartDao cartDao = new CartDao(ConnectionProvider.getConnection());
				int cartCount = cartDao.getCartCountByUserId(user.getUserId());
			
      out.write("\n");
      out.write("			<ul class=\"navbar-nav ml-auto\">\n");
      out.write("				<li class=\"nav-item active pe-3\"><a\n");
      out.write("					class=\"nav-link position-relative\" aria-current=\"page\"\n");
      out.write("					href=\"cart.jsp\"><i class=\"fa-solid fa-cart-shopping\"\n");
      out.write("						style=\"color: #ffffff;\"></i> &nbsp;Cart<span\n");
      out.write("						class=\"position-absolute top-1 start-0 translate-middle badge rounded-pill bg-danger\">");
      out.print(cartCount);
      out.write("</span></a></li>\n");
      out.write("				<li class=\"nav-item active pe-3\"><a class=\"nav-link\"\n");
      out.write("					aria-current=\"page\" href=\"profile.jsp\">");
      out.print(user.getUserName());
      out.write("</a></li>\n");
      out.write("				<li class=\"nav-item pe-3\"><a class=\"nav-link\"\n");
      out.write("					aria-current=\"page\" href=\"LogoutServlet?user=user\"><i\n");
      out.write("						class=\"fa-solid fa-user-slash\" style=\"color: #fafafa;\"></i>&nbsp;Logout</a></li>\n");
      out.write("			</ul>\n");
      out.write("			");

			} else {
			
      out.write("\n");
      out.write("			<ul class=\"navbar-nav ml-auto\">\n");
      out.write("				<li class=\"nav-item active pe-2\"><a class=\"nav-link\"\n");
      out.write("					aria-current=\"page\" href=\"register.jsp\"> <i\n");
      out.write("						class=\"fa-solid fa-user-plus\" style=\"color: #ffffff;\"></i>&nbsp;Register\n");
      out.write("				</a></li>\n");
      out.write("				<li class=\"nav-item pe-2\"><a class=\"nav-link\"\n");
      out.write("					aria-current=\"page\" href=\"login.jsp\"><i\n");
      out.write("						class=\"fa-solid fa-user-lock\" style=\"color: #fafafa;\"></i>&nbsp;Login</a></li>\n");
      out.write("				<li class=\"nav-item pe-2\"><a class=\"nav-link\"\n");
      out.write("					aria-current=\"page\" href=\"adminlogin.jsp\">&nbsp;Admin</a></li>\n");
      out.write("			</ul>\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	");

	}
	}
	
      out.write("\n");
      out.write("	<!-- end  -->\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"container mt-5\" style=\"font-size: 17px;\">\n");
      out.write("		<div class=\"row\">\n");
      out.write("\n");
      out.write("			<!-- left column -->\n");
      out.write("			<div class=\"col-md-8\">\n");
      out.write("				<div class=\"card\">\n");
      out.write("					<div class=\"container px-3 py-3\">\n");
      out.write("						<div class=\"card\">\n");
      out.write("							<div class=\"container-fluid text-white\"\n");
      out.write("								style=\"background-color: #389aeb;\">\n");
      out.write("								<h4>Delivery Address</h4>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"mt-3 mb-3\">\n");
      out.write("							<h5>");
      out.print(user.getUserName());
      out.write("\n");
      out.write("								&nbsp;\n");
      out.write("								");
      out.print(user.getUserPhone());
      out.write("</h5>\n");
      out.write("							");

							StringBuilder str = new StringBuilder();
							str.append(user.getUserAddress() + ", ");
							str.append(user.getUserCity() + ", ");
							str.append(user.getUserCity() + ", ");
							str.append(user.getUserPincode());
							out.println(str);
							
      out.write("\n");
      out.write("							<br>\n");
      out.write("							<div class=\"text-end\">\n");
      out.write("								<button type=\"button\" class=\"btn btn-outline-primary\"\n");
      out.write("									data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">\n");
      out.write("									Change Address</button>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<hr>\n");
      out.write("						<div class=\"card\">\n");
      out.write("							<div class=\"container-fluid text-white\"\n");
      out.write("								style=\"background-color: #389aeb;\">\n");
      out.write("								<h4>Payment Options</h4>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<form action=\"OrderOperationServlet\" method=\"post\">\n");
      out.write("							<div class=\"form-check mt-2\">\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\" name=\"payementMode\"\n");
      out.write("									value=\"Card Payment\" required><label class=\"form-check-label\">Credit\n");
      out.write("									/Debit /ATM card</label><br>\n");
      out.write("								<div class=\"mb-3\">\n");
      out.write("\n");
      out.write("									<input class=\"form-control mt-3\" type=\"number\"\n");
      out.write("										placeholder=\"Enter card number\" name=\"cardno\">\n");
      out.write("									<div class=\"row gx-5\">\n");
      out.write("										<div class=\"col mt-3\">\n");
      out.write("											<input class=\"form-control\" type=\"number\"\n");
      out.write("												placeholder=\"Enter CVV\" name=\"cvv\">\n");
      out.write("										</div>\n");
      out.write("										<div class=\"col mt-3\">\n");
      out.write("											<input class=\"form-control\" type=\"text\"\n");
      out.write("												placeholder=\"Valid through i.e '07/23'\">\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("									<input class=\"form-control mt-3\" type=\"text\"\n");
      out.write("										placeholder=\"Enter card holder name\" name=\"name\">\n");
      out.write("								</div>\n");
      out.write("								<input class=\"form-check-input\" type=\"radio\" name=\"payementMode\"\n");
      out.write("									value=\"Cash on Delivery\"><label\n");
      out.write("									class=\"form-check-label\">Cash on Delivery</label>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"text-end\">\n");
      out.write("								<button type=\"submit\"\n");
      out.write("									class=\"btn btn-lg btn-outline-primary mt-3\">Place\n");
      out.write("									Order</button>\n");
      out.write("							</div>\n");
      out.write("						</form>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!-- end of column -->\n");
      out.write("\n");
      out.write("			<!-- right column -->\n");
      out.write("			<div class=\"col-md-4\">\n");
      out.write("				<div class=\"card\">\n");
      out.write("					<div class=\"container px-3 py-3\">\n");
      out.write("						<h4>Price Details</h4>\n");
      out.write("						<hr>\n");
      out.write("						");

						if (from.trim().equals("cart")) {
							CartDao cartDao = new CartDao(ConnectionProvider.getConnection());
							int totalProduct = cartDao.getCartCountByUserId(user.getUserId());
							float totalPrice = (float) session.getAttribute("totalPrice");
						
      out.write("\n");
      out.write("						<table class=\"table table-borderless\">\n");
      out.write("							<tr>\n");
      out.write("								<td>Total Item</td>\n");
      out.write("								<td>");
      out.print(totalProduct);
      out.write("</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>Total Price</td>\n");
      out.write("								<td>&#8377; ");
      out.print(totalPrice);
      out.write("</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>Delivery Charges</td>\n");
      out.write("								<td>&#8377; 40</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>Packaging Charges</td>\n");
      out.write("								<td>&#8377; 29</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td><h5>Amount Payable :</h5></td>\n");
      out.write("								<td><h5>\n");
      out.write("										&#8377;\n");
      out.write("										");
      out.print(totalPrice + 69);
      out.write("</h5></td>\n");
      out.write("							</tr>\n");
      out.write("						</table>\n");
      out.write("						");

						} else {
							ProductDao productDao = new ProductDao(ConnectionProvider.getConnection());
							int pid = (int) session.getAttribute("pid");
							float price = productDao.getProductPriceById(pid);
						
      out.write("\n");
      out.write("						<table class=\"table table-borderless\">\n");
      out.write("							<tr>\n");
      out.write("								<td>Total Item</td>\n");
      out.write("								<td>1</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>Total Price</td>\n");
      out.write("								<td>&#8377; ");
      out.print(price);
      out.write("</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>Delivery Charges</td>\n");
      out.write("								<td>&#8377; 40</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td>Packaging Charges</td>\n");
      out.write("								<td>&#8377; 29</td>\n");
      out.write("							</tr>\n");
      out.write("							<tr>\n");
      out.write("								<td><h5>Amount Payable :</h5></td>\n");
      out.write("								<td><h5>\n");
      out.write("										&#8377;\n");
      out.write("										");
      out.print(price + 69);
      out.write("</h5></td>\n");
      out.write("							</tr>\n");
      out.write("						</table>\n");
      out.write("						");

						}
						
      out.write("\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!-- end of column -->\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!--Change Address Modal -->\n");
      out.write("	<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\"\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header\">\n");
      out.write("					<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Change\n");
      out.write("						Address</h1>\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\"></button>\n");
      out.write("				</div>\n");
      out.write("				<form action=\"UpdateUserServlet\" method=\"post\">\n");
      out.write("					<input type=\"hidden\" name=\"operation\" value=\"changeAddress\">\n");
      out.write("					<div class=\"modal-body mx-3\">\n");
      out.write("						<div class=\"mt-2\">\n");
      out.write("							<label class=\"form-label fw-bold\">Address</label>\n");
      out.write("							<textarea name=\"user_address\" rows=\"3\"\n");
      out.write("								placeholder=\"Enter Address(Area and Street))\"\n");
      out.write("								class=\"form-control\" required></textarea>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"mt-2\">\n");
      out.write("							<label class=\"form-label fw-bold\">City</label> <input\n");
      out.write("								class=\"form-control\" type=\"text\" name=\"city\"\n");
      out.write("								placeholder=\"City/District/Town\" required>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"mt-2\">\n");
      out.write("							<label class=\"form-label fw-bold\">Pincode</label> <input\n");
      out.write("								class=\"form-control\" type=\"number\" name=\"pincode\"\n");
      out.write("								placeholder=\"Pincode\" maxlength=\"6\" required>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"mt-2\">\n");
      out.write("							<label class=\"form-label fw-bold\">State</label> <select\n");
      out.write("								name=\"state\" class=\"form-select\">\n");
      out.write("								<option selected>--Select State--</option>\n");
      out.write("								<option value=\"Andaman &amp; Nicobar Islands\">Andaman\n");
      out.write("									&amp; Nicobar Islands</option>\n");
      out.write("								<option value=\"Andhra Pradesh\">Andhra Pradesh</option>\n");
      out.write("								<option value=\"Arunachal Pradesh\">Arunachal Pradesh</option>\n");
      out.write("								<option value=\"Assam\">Assam</option>\n");
      out.write("								<option value=\"Bihar\">Bihar</option>\n");
      out.write("								<option value=\"Chandigarh\">Chandigarh</option>\n");
      out.write("								<option value=\"Chhattisgarh\">Chhattisgarh</option>\n");
      out.write("								<option value=\"Dadra &amp; Nagar Haveli &amp; Daman &amp; Diu\">Dadra\n");
      out.write("									&amp; Nagar Haveli &amp; Daman &amp; Diu</option>\n");
      out.write("								<option value=\"Delhi\">Delhi</option>\n");
      out.write("								<option value=\"Goa\">Goa</option>\n");
      out.write("								<option value=\"Gujarat\">Gujarat</option>\n");
      out.write("								<option value=\"Haryana\">Haryana</option>\n");
      out.write("								<option value=\"Himachal Pradesh\">Himachal Pradesh</option>\n");
      out.write("								<option value=\"Jammu &amp; Kashmir\">Jammu &amp; Kashmir</option>\n");
      out.write("								<option value=\"Jharkhand\">Jharkhand</option>\n");
      out.write("								<option value=\"Karnataka\">Karnataka</option>\n");
      out.write("								<option value=\"Kerala\">Kerala</option>\n");
      out.write("								<option value=\"Ladakh\">Ladakh</option>\n");
      out.write("								<option value=\"Lakshadweep\">Lakshadweep</option>\n");
      out.write("								<option value=\"Madhya Pradesh\">Madhya Pradesh</option>\n");
      out.write("								<option value=\"Maharashtra\">Maharashtra</option>\n");
      out.write("								<option value=\"Manipur\">Manipur</option>\n");
      out.write("								<option value=\"Meghalaya\">Meghalaya</option>\n");
      out.write("								<option value=\"Mizoram\">Mizoram</option>\n");
      out.write("								<option value=\"Nagaland\">Nagaland</option>\n");
      out.write("								<option value=\"Odisha\">Odisha</option>\n");
      out.write("								<option value=\"Puducherry\">Puducherry</option>\n");
      out.write("								<option value=\"Punjab\">Punjab</option>\n");
      out.write("								<option value=\"Rajasthan\">Rajasthan</option>\n");
      out.write("								<option value=\"Sikkim\">Sikkim</option>\n");
      out.write("								<option value=\"Tamil Nadu\">Tamil Nadu</option>\n");
      out.write("								<option value=\"Telangana\">Telangana</option>\n");
      out.write("								<option value=\"Tripura\">Tripura</option>\n");
      out.write("								<option value=\"Uttarakhand\">Uttarakhand</option>\n");
      out.write("								<option value=\"Uttar Pradesh\">Uttar Pradesh</option>\n");
      out.write("								<option value=\"West Bengal\">West Bengal</option>\n");
      out.write("							</select>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-footer\">\n");
      out.write("						<button type=\"button\" class=\"btn btn-secondary\"\n");
      out.write("							data-bs-dismiss=\"modal\">Close</button>\n");
      out.write("						<button type=\"submit\" class=\"btn btn-primary\">Save</button>\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- end modal -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
