/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-06-05 03:33:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Home</title>\n");
      out.write("<link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@9\"></script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".cus-card {\n");
      out.write("	border-radius: 50%;\n");
      out.write("	border-color: transparent;\n");
      out.write("	max-height: 200px;\n");
      out.write("	max-width: 200px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".real-price {\n");
      out.write("	font-size: 20px !important;\n");
      out.write("	font-weight: 600;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".product-price {\n");
      out.write("	font-size: 17px !important;\n");
      out.write("	text-decoration: line-through;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".product-discount {\n");
      out.write("	font-size: 15px !important;\n");
      out.write("	color: #027a3e;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!--navbar -->\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("		<a class=\"navbar-brand\" href=\"#\">Navbar</a>\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("		</button>\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n");
      out.write("			<ul class=\"navbar-nav\">\n");
      out.write("				<li class=\"nav-item active\">\n");
      out.write("					<a class=\"nav-link\" href=\"#\">Home <span class=\"sr-only\">(current)</span></a>\n");
      out.write("				</li>\n");
      out.write("				<li class=\"nav-item\">\n");
      out.write("					<a class=\"nav-link\" href=\"#\">Features</a>\n");
      out.write("				</li>\n");
      out.write("				<li class=\"nav-item\">\n");
      out.write("					<a class=\"nav-link\" href=\"#\">Pricing</a>\n");
      out.write("				</li>\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("\n");
      out.write("	<!-- Category list -->\n");
      out.write("	<div class=\"container-fluid px-3 py-3\" style=\"background-color: #e3f7fc;\">\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"card-group\">\n");
      out.write("				<!-- Repeat for each category -->\n");
      out.write("				<div class=\"col text-center\">\n");
      out.write("					<a href=\"products.jsp?category=1\" style=\"text-decoration: none;\">\n");
      out.write("						<div class=\"card cus-card h-100\">\n");
      out.write("							<div class=\"container text-center\">\n");
      out.write("								<img src=\"Product_imgs/category_image.jpg\" class=\"mt-3\" style=\"max-width: 100%; max-height: 100px; width: auto; height: auto;\">\n");
      out.write("							</div>\n");
      out.write("							<h6>Category Name</h6>\n");
      out.write("						</div>\n");
      out.write("					</a>\n");
      out.write("				</div>\n");
      out.write("				<!-- End repeat -->\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- end of list -->\n");
      out.write("\n");
      out.write("	<!-- Carousel -->\n");
      out.write("	<div id=\"carouselAutoplaying\" class=\"carousel slide carousel-dark mt-3 mb-3\" data-bs-ride=\"carousel\">\n");
      out.write("		<div class=\"carousel-inner\">\n");
      out.write("			<div class=\"carousel-item active\">\n");
      out.write("				<img src=\"Images/scroll_img2.png\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"carousel-item\">\n");
      out.write("				<img src=\"Images/scroll_img1.png\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"carousel-item\">\n");
      out.write("				<img src=\"Images/scroll_img3.png\" class=\"d-block w-100\" alt=\"...\">\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselAutoplaying\" data-bs-slide=\"prev\">\n");
      out.write("			<span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span> \n");
      out.write("			<span class=\"visually-hidden\">Previous</span>\n");
      out.write("		</button>\n");
      out.write("		<button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselAutoplaying\" data-bs-slide=\"next\">\n");
      out.write("			<span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span> \n");
      out.write("			<span class=\"visually-hidden\">Next</span>\n");
      out.write("		</button>\n");
      out.write("	</div>\n");
      out.write("	<!-- end of carousel -->\n");
      out.write("\n");
      out.write("	<!-- latest product listed -->\n");
      out.write("	<div class=\"container-fluid py-3 px-3\" style=\"background: #f2f2f2;\">\n");
      out.write("		<div class=\"row row-cols-1 row-cols-md-4 g-3\">\n");
      out.write("			<div class=\"col\">\n");
      out.write("				<div class=\"container text-center px-5 py-5\">\n");
      out.write("					<h1>Latest Products</h1>\n");
      out.write("					<img src=\"Images/product.png\" class=\"card-img-top\" style=\"max-width: 100%; max-height: 200px; width: auto;\">\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!-- Repeat for each latest product -->\n");
      out.write("			<div class=\"col\">\n");
      out.write("				<a href=\"viewProduct.jsp?pid=1\" style=\"text-decoration: none;\">\n");
      out.write("					<div class=\"card h-100\">\n");
      out.write("						<div class=\"container text-center\">\n");
      out.write("							<img src=\"Product_imgs/product_image.jpg\" class=\"card-img-top m-2\" style=\"max-width: 100%; max-height: 200px; width: auto;\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"card-body\">\n");
      out.write("							<h5 class=\"card-title text-center\">Product Name</h5>\n");
      out.write("							<div class=\"container text-center\">\n");
      out.write("								<span class=\"real-price\">&#8377;1000</span>\n");
      out.write("								&ensp;<span class=\"product-price\">&#8377;1200</span>\n");
      out.write("								&ensp;<span class=\"product-discount\">20&#37; off</span>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</a>\n");
      out.write("			</div>\n");
      out.write("			<!-- End repeat -->\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- end of list -->\n");
      out.write("\n");
      out.write("	<!-- product with heavy deals -->\n");
      out.write("	<div class=\"container-fluid py-3 px-3\" style=\"background: #f0fffe;\">\n");
      out.write("		<h3>Hot Deals</h3>\n");
      out.write("		<div class=\"row row-cols-1 row-cols-md-4 g-3\">\n");
      out.write("			<!-- Repeat for each hot deal -->\n");
      out.write("			<div class=\"col\">\n");
      out.write("				<a href=\"viewProduct.jsp?pid=2\" style=\"text-decoration: none;\">\n");
      out.write("					<div class=\"card h-100\">\n");
      out.write("						<div class=\"container text-center\">\n");
      out.write("							<img src=\"Product_imgs/hot_deal_image.jpg\" class=\"card-img-top m-2\" style=\"max-width: 100%; max-height: 200px; width: auto;\">\n");
      out.write("						</div>\n");
      out.write("						<div class=\"card-body\">\n");
      out.write("							<h5 class=\"card-title text-center\">Product Name</h5>\n");
      out.write("							<div class=\"container text-center\">\n");
      out.write("								<span class=\"real-price\">&#8377;800</span>\n");
      out.write("								&ensp;<span class=\"product-price\">&#8377;1000</span>\n");
      out.write("								&ensp;<span class=\"product-discount\">20&#37; off</span>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</a>\n");
      out.write("			</div>\n");
      out.write("			<!-- End repeat -->\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- end -->\n");
      out.write("\n");
      out.write("	<!-- confirmation message for successful order -->\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		// Simulating order placement success\n");
      out.write("		var orderPlaced = true; // This should be dynamically set based on actual order status\n");
      out.write("\n");
      out.write("		if (orderPlaced) {\n");
      out.write("			Swal.fire({\n");
      out.write("				icon : 'success',\n");
      out.write("				title: 'Order Placed, Thank you!',\n");
      out.write("				text: 'Confirmation will be sent to your email',\n");
      out.write("				width: 600,\n");
      out.write("				padding: '3em',\n");
      out.write("				showConfirmButton : false,\n");
      out.write("				timer : 3500,\n");
      out.write("				backdrop: `rgba(0,0,123,0.4)`\n");
      out.write("			});\n");
      out.write("		}\n");
      out.write("	</script>\n");
      out.write("	<!-- end of message -->\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
